# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

vs_multiallelic_Rcpp <- function(PH, GENO, pedigree) {
    .Call('_mappolymp_vs_multiallelic_Rcpp', PACKAGE = 'mappolymp', PH, GENO, pedigree)
}

vs_biallelic_Rcpp <- function(PH, G, pedigree) {
    .Call('_mappolymp_vs_biallelic_Rcpp', PACKAGE = 'mappolymp', PH, G, pedigree)
}

